### ISSUE TITLE
Cant zoom when distance hit 0.00 and minimumDistance is set to 0

### ISSUE THREAD

**Issue by eskimoblood** [jdf/peasycam#15]
The following line is used to calculate the distance on zoom: 

```
private void mouseZoom(final double delta) {
    safeSetDistance(distance + delta * Math.log1p(distance));
}
```

So, when the distance is `0` and the minimumDistance is also `0` or lower you cant zoom out anymore. Also minimumDistance lower then `0` will cause distance to be `NaN` in some cases.

**Comment by jdf** [comment]
Pushed in version 201.
