### ISSUE TITLE
Processing is not showing up peasycam

### ISSUE THREAD

**Issue by fmvilas** [jdf/peasycam#22]
I've found that trying to import library in latter versions of Processing result in not found. Check it:

<img width="445" alt="screen shot 2015-09-23 at 21 14 05" src="https://cloud.githubusercontent.com/assets/242119/10055748/3ac328e4-6238-11e5-8979-61b36fbadfa4.png">

Can you please provide the jar file meanwhile?

Thanks!

**Comment by jdf** [comment]
Is this still the case?

**Comment by fmvilas** [comment]
I don't know. I'm not using Processing for a while sorry.
