### ISSUE TITLE
Y axis still vertical ?

### ISSUE THREAD

**Issue by KoiKoiDesign** [jdf/peasycam#29]
Hi Jonathan,

I'm currently using your library but I didn't find at yet how to set up correctly the camera.
I explain : I want to set up the cam wich Y axis stays vertical. I allready built my  own cam [here](https://www.openprocessing.org/sketch/391390) , with the Y axis allways vertical.
I didn't find how to do that with Peasycam. 

Thanks for your answer !

Clément 

(btw I try differents set up and apparently camera.setSuppressRollRotationMode() did nothing different to the free mode an my computer)

**Comment by jdf** [comment]
Perhaps `camera.setYawRotationMode()`?

**Comment by KoiKoiDesign** [comment]
Hi Jonathan,

thanks for your answer !

I try `camera.setYawRotationMode()` but in this case, the camera is turning only around Y axis (with mouseX). If you check my [cam](https://www.openprocessing.org/sketch/391390) on OpenProcessing, the cam is turning around Y axis with mouseX dragged and it also turning with mouseY dragged.
According to you, is it possible to do the same with peasyCam ? Maybe there is a coding (or magic) trick…

Clément

**Comment by jdf** [comment]
I don't see how the "Y axis is always vertical" in your sketch.
