### ISSUE TITLE
How lookAt work? Is possible look points in movement?

### ISSUE THREAD

**Issue by Maharal** [jdf/peasycam#31]
I need to change the target of camera, but don't work. Why?

cam.lookAt(target.x, target.y += 1.5, target.z);
println(target.x +","+ target.y +","+ target.z);

**Comment by jdf** [comment]
It's very suspicious to have that `+=` operation in the middle of that expression. It's unclear what you're hoping to do, and you don't say what happens, or what you expect to happen.

What would best help me help you would be a small, complete example program that demonstrates the broken behavior.
