### ISSUE TITLE
mouse position to cam position

### ISSUE THREAD

**Issue by nevahid** [jdf/peasycam#37]
hi everybody... i have a question, i want to map current mouse position to a position a camera view... the main goal is to let people drag things from a 2D canvas to the 3D space...
i would really thank you if you can give me any help...
@jdf  and thanks for your wonderful library...

**Comment by jdf** [comment]
This question should probably go to the Processing forum instead.

**Comment by jdf** [comment]
Also, thanks for the kind word. :)

**Comment by nevahid** [comment]
@jdf, thanks for your response... i'm deep into the problem and learned a lot in the process :-) thanks again
